feat: add writing managed accounts feature in terraform provider
BeyondTrust/go-client-library-passwordsafe pull request #152
Opened 2024-11-05 23:47 UTC by btfhernandez

2024-11-06 22:27 UTC, dtejadav requested changes

2024-11-06 22:27 UTC, dtejadav commented on api/managed_account/managed_account.go
> +	ManagedAccountSytemUrl := managedAccounObj.authenticationObj.ApiUrl.JoinPath("ManagedSystems").String()
Typo "Sytem"

2024-11-06 22:27 UTC, dtejadav commented on api/managed_account/managed_account.go
> +	ManagedAccountCreateManagedAccountUrl := managedAccounObj.authenticationObj.ApiUrl.JoinPath("ManagedSystems", fmt.Sprintf("%d", managedSystem.ManagedSystemID), "ManagedAccounts").String()
Typo "Accoun"

2024-11-06 22:27 UTC, dtejadav commented on api/managed_account/managed_account.go
> +func (managedAccounObj *ManagedAccountstObj) ManagedAccountCreateManagedAccount(accountDetails entities.AccountDetails, url string) (entities.CreateManagedAccountsResponse, error) {
Typo "Accoun"

2024-11-06 22:27 UTC, dtejadav commented on api/managed_account/managed_account.go
> +		body, _, technicalError, businessError = managedAccounObj.authenticationObj.HttpClient.CallSecretSafeAPI(url, "POST", *b, "ManagedAccountCreateManagedAccount", "", "")
Typo "Accoun"

2024-11-07 13:09 UTC, RanjitMishraBT commented on api/managed_account/managed_account.go
> +	managedSystemGetSystemsResponse, err := managedAccounObj.ManagedSystemGetSystems(ManagedAccountSytemUrl)
typo "Accoun"

2024-11-08 13:54 UTC, dtejadav approved these changes
Nice work!

2024-11-08 14:02 UTC, merged